name: AurumSlots
version: '1.1.2'
main: org.ChisaO_o.simpleSlots.SimpleSlots
api-version: '26.2'
description: Плагин на кастомные слот-машины через полки
softdepend: [Vault, VaultUnlocked]

commands:
  slots:
    description: Управление слот-машинами
    usage: /slots help
    aliases: [aurumslots]
    permission: casino.admin

permissions:
  casino.admin:
    description: Позволяет настраивать слот-машины
    default: op
